services:
  php:
    build:
     context: .
     dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d:ro
    restart: unless-stopped
    depends_on:
      - python
  nginx:
    image: nginx:alpine
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./app:/var/www/html:ro
     - ./docker/nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
     - ./certbot/www:/var/www/certbot
     - ./certbot/conf:/etc/letsencrypt
    depends_on:
     - php
    restart: unless-stopped
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - "./app/public/2lab/python:/app"
    user: "1000:1000"
    restart: unless-stopped